### ISSUE TITLE
mamFetch/mamFetchAll function mismatch parameter

### ISSUE THREAD

**Issue by sdellava** [iotaledger/mam.js#15]
In the API description (here https://github.com/iotaledger/mam.js/blob/chrysalis/docs/modules/mam_client.md#mamfetch)

both mamFetch and mamFetchAll api require a client parameter in format iclient or string.

both functions do not work if the client is passed as iclient, obtained from a SingleNodeClient(iotanode) function; 

Functions work only if the client is passed as string containing the IOTA node api's url

I suggest to amend the documentation.

**Comment by obany** [comment]
I locally modified the example https://github.com/iotaledger/mam.js/blob/chrysalis/examples/simple/index.js

Added import
```
const { SingleNodeClient } = require("@iota/iota.js")
```

and changed the attach line to

```
const { messageId } = await mamAttach(new SingleNodeClient(node), mamMessage, "MY9MAM");
```

This worked as expected, what error are you seeing ?

**Comment by sdellava** [comment]
**Here my test script. Pls try it:**

const { SingleNodeClient } = require('@iota/iota.js');
const { mamFetchAll } = require('@iota/mam-chrysalis.js');

const mode = 'public'
const sideKey = ''
const provider = 'https://api.hornet-0.testnet.chrysalis2.com'

var initialRoot = "LQIQYBJIMMPGWXHFEMTQCTVXDLCHBHFXATRJFCEBGUAOKFJYPEGLGBQ9NDZSPIICRBUOLTJ9UOWYMUSKR"
var channelMessages

const run = async () => {


    channelMessages = await mamFetchAll(new SingleNodeClient(provider), initialRoot, mode, sideKey);

    console.log("messages in the channel using client: ", channelMessages.length)

    channelMessages = await mamFetchAll(provider, initialRoot, mode, sideKey);

    console.log("messages in the channel using provider: ", channelMessages.length)
}

run()

**this is the output:**

mam chrysalis>node test.js
messages in the channel using client:  0
messages in the channel using provider:  24

**Comment by obany** [comment]
The problem you are seeing is because `mamFetchAll` did not support client or node as input, `mamFetch` does, which is how it is documented (the documents are auto generated from the code). 

I have added the ability for `mamFetchAll` to support both methods as well in the commit https://github.com/iotaledger/mam.js/commit/3e23153ea1c2323e01414bdab7c3a1965b63dc4d

The iota.js dependencies were also slightly out of date, so the SingleNodeClient created by the example and internally were treated differently.

Running your example now produces this output

```
messages in the channel using client:  24
messages in the channel using provider:  24
```
