### ISSUE TITLE
Files in dist throw error

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/mam.js#4]
Uncaught TypeError: bigInt is not a function

**Comment by obany** [comment]
Can you provide any more details, I just performed the following successfully:

Created a new folder
`npm install @iota/mam.js`
copied the simple code example https://github.com/iotaledger/mam.js/blob/master/examples/simple/index.js
executed `node index.js`

**Comment by Thoralf-M** [comment]
Oh so this is just for nodejs? I thought it was for the browser, my fault

**Comment by obany** [comment]
It is a module so won't work if you include directly in browser with a script tag. But it will work if you use some kind of package manager for a web app.

**Comment by nothingismagick** [comment]
I think that the takeaway for me is that the README needs to offer clarity on the matter and potentially a vetted method of packaging for a web app.

**Comment by dysbulic** [comment]
I'm able to run the code from the [example](https://github.com/iotaledger/mam.js/blob/master/examples/simple/index.js) in a browser using `import { channelRoot, createChannel, createMessage, parseMessage, mamAttach, mamFetch, mamFetchAll } from '@iota/mam.js'`.

**Comment by obany** [comment]
Since the `@iota` core js libraries don't have a version that work directly in the browser I have built an additional version of this library `mam.browser.js` which includes the necessary parts of the `@iota` libs. The `big-integer` package is still referenced externally as this is available from CDNs.

There is a fully working example on how to use this new distribution here https://github.com/iotaledger/mam.js/blob/master/examples/browser/index.html
